version: "3.0"
services:
  cv-aio-env:
    image: qiangzibro/cv-aio:latest
    build:
        context: ./
        dockerfile: Dockerfile
    volumes:
        - .:/workspace
    tty: true
    network_mode: "host"
    environment:
      - "http_proxy=${http_proxy}"
      - "https_proxy=${https_proxy}"
    entrypoint: sh -c "jupyter lab --ip=0.0.0.0 --port=11000 --no-browser --notebook-dir=/workspace --allow-root --NotebookApp.token='cv-aio' --NotebookApp.password='cv-aio'"
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
